#ifndef H__HelloWorld_r00iaxum_dll
#define H__HelloWorld_r00iaxum_dll
#include "CoreLib.h"

struct HelloWorld;
struct System_Collections_Generic_IEnumerableGSystem_StringC;
struct System_Collections_Generic_ICollectionGSystem_StringC;
struct System_Collections_Generic_IListGSystem_StringC;
struct System_Collections_Generic_IReadOnlyCollectionGSystem_StringC;
struct System_Collections_Generic_IReadOnlyListGSystem_StringC;
struct System_StringAY;
struct System_ArraySegmentGSystem_StringC__struct_data;
struct System_ArraySegmentGSystem_StringC;
struct System_Collections_Generic_IEnumeratorGSystem_StringC;
struct System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator;
struct System_Collections_Generic_IEnumerableGSystem_Int32C;
struct System_Collections_Generic_ICollectionGSystem_Int32C;
struct System_Collections_Generic_IListGSystem_Int32C;
struct System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C;
struct System_Collections_Generic_IReadOnlyListGSystem_Int32C;
struct System_Int32AY;
struct System_Collections_Generic_IEnumerableGSystem_ByteC;
struct System_Collections_Generic_ICollectionGSystem_ByteC;
struct System_Collections_Generic_IListGSystem_ByteC;
struct System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC;
struct System_Collections_Generic_IReadOnlyListGSystem_ByteC;
struct System_ByteAY;
struct System_ArraySegmentGSystem_Int32C__struct_data;
struct System_ArraySegmentGSystem_Int32C;
struct System_Collections_Generic_IEnumeratorGSystem_Int32C;
struct System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator;
struct System_ArraySegmentGSystem_ByteC__struct_data;
struct System_ArraySegmentGSystem_ByteC;
struct System_Collections_Generic_IEnumeratorGSystem_ByteC;
struct System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator;
#ifndef VTBL__System_Collections_Generic_IEnumerableGSystem_StringC
#define VTBL__System_Collections_Generic_IEnumerableGSystem_StringC
struct System_Collections_Generic_IEnumerableGSystem_StringC__vtbl {
    System_Collections_IEnumerable__vtbl ifce_System_Collections_IEnumerable;
    System_Collections_Generic_IEnumeratorGSystem_StringC* (*System_Collections_Generic_IEnumeratorGSystem_StringC_System_Collections_Generic_IEnumerableGSystem_StringC_GetEnumeratorFN)(System_Collections_Generic_IEnumerableGSystem_StringC*);
    System_Object* (*System_Object_System_Collections_Generic_IEnumerableGSystem_StringC__dynifaceFSystem_TypeN)(System_Collections_Generic_IEnumerableGSystem_StringC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_ICollectionGSystem_StringC
#define VTBL__System_Collections_Generic_ICollectionGSystem_StringC
struct System_Collections_Generic_ICollectionGSystem_StringC__vtbl {
    System_Collections_Generic_IEnumerableGSystem_StringC__vtbl ifce_System_Collections_Generic_IEnumerableGSystem_StringC;
    Int32 (*Int32_System_Collections_Generic_ICollectionGSystem_StringC_get_CountFN)(System_Collections_Generic_ICollectionGSystem_StringC*);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_StringC_get_IsReadOnlyFN)(System_Collections_Generic_ICollectionGSystem_StringC*);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_StringC_AddFSystem_StringN)(System_Collections_Generic_ICollectionGSystem_StringC*, System_String*);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_StringC_ClearFN)(System_Collections_Generic_ICollectionGSystem_StringC*);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_StringC_ContainsFSystem_StringN)(System_Collections_Generic_ICollectionGSystem_StringC*, System_String*);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_StringC_CopyToFSystem_StringAY__Int32N)(System_Collections_Generic_ICollectionGSystem_StringC*, System_StringAY*, Int32);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_StringC_RemoveFSystem_StringN)(System_Collections_Generic_ICollectionGSystem_StringC*, System_String*);
    System_Object* (*System_Object_System_Collections_Generic_ICollectionGSystem_StringC__dynifaceFSystem_TypeN)(System_Collections_Generic_ICollectionGSystem_StringC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IListGSystem_StringC
#define VTBL__System_Collections_Generic_IListGSystem_StringC
struct System_Collections_Generic_IListGSystem_StringC__vtbl {
    System_Collections_Generic_ICollectionGSystem_StringC__vtbl ifce_System_Collections_Generic_ICollectionGSystem_StringC;
    System_String* (*System_String_System_Collections_Generic_IListGSystem_StringC_get_ItemFInt32N)(System_Collections_Generic_IListGSystem_StringC*, Int32);
    Void (*Void_System_Collections_Generic_IListGSystem_StringC_set_ItemFInt32__System_StringN)(System_Collections_Generic_IListGSystem_StringC*, Int32, System_String*);
    Int32 (*Int32_System_Collections_Generic_IListGSystem_StringC_IndexOfFSystem_StringN)(System_Collections_Generic_IListGSystem_StringC*, System_String*);
    Void (*Void_System_Collections_Generic_IListGSystem_StringC_InsertFInt32__System_StringN)(System_Collections_Generic_IListGSystem_StringC*, Int32, System_String*);
    Void (*Void_System_Collections_Generic_IListGSystem_StringC_RemoveAtFInt32N)(System_Collections_Generic_IListGSystem_StringC*, Int32);
    System_Object* (*System_Object_System_Collections_Generic_IListGSystem_StringC__dynifaceFSystem_TypeN)(System_Collections_Generic_IListGSystem_StringC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IReadOnlyCollectionGSystem_StringC
#define VTBL__System_Collections_Generic_IReadOnlyCollectionGSystem_StringC
struct System_Collections_Generic_IReadOnlyCollectionGSystem_StringC__vtbl {
    System_Collections_Generic_IEnumerableGSystem_StringC__vtbl ifce_System_Collections_Generic_IEnumerableGSystem_StringC;
    Int32 (*Int32_System_Collections_Generic_IReadOnlyCollectionGSystem_StringC_get_CountFN)(System_Collections_Generic_IReadOnlyCollectionGSystem_StringC*);
    System_Object* (*System_Object_System_Collections_Generic_IReadOnlyCollectionGSystem_StringC__dynifaceFSystem_TypeN)(System_Collections_Generic_IReadOnlyCollectionGSystem_StringC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IReadOnlyListGSystem_StringC
#define VTBL__System_Collections_Generic_IReadOnlyListGSystem_StringC
struct System_Collections_Generic_IReadOnlyListGSystem_StringC__vtbl {
    System_Collections_Generic_IReadOnlyCollectionGSystem_StringC__vtbl ifce_System_Collections_Generic_IReadOnlyCollectionGSystem_StringC;
    System_String* (*System_String_System_Collections_Generic_IReadOnlyListGSystem_StringC_get_ItemFInt32N)(System_Collections_Generic_IReadOnlyListGSystem_StringC*, Int32);
    System_Object* (*System_Object_System_Collections_Generic_IReadOnlyListGSystem_StringC__dynifaceFSystem_TypeN)(System_Collections_Generic_IReadOnlyListGSystem_StringC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IEnumeratorGSystem_StringC
#define VTBL__System_Collections_Generic_IEnumeratorGSystem_StringC
struct System_Collections_Generic_IEnumeratorGSystem_StringC__vtbl {
    System_IDisposable__vtbl ifce_System_IDisposable;
    System_Collections_IEnumerator__vtbl ifce_System_Collections_IEnumerator;
    System_String* (*System_String_System_Collections_Generic_IEnumeratorGSystem_StringC_get_CurrentFN)(System_Collections_Generic_IEnumeratorGSystem_StringC*);
    System_Object* (*System_Object_System_Collections_Generic_IEnumeratorGSystem_StringC__dynifaceFSystem_TypeN)(System_Collections_Generic_IEnumeratorGSystem_StringC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IEnumerableGSystem_Int32C
#define VTBL__System_Collections_Generic_IEnumerableGSystem_Int32C
struct System_Collections_Generic_IEnumerableGSystem_Int32C__vtbl {
    System_Collections_IEnumerable__vtbl ifce_System_Collections_IEnumerable;
    System_Collections_Generic_IEnumeratorGSystem_Int32C* (*System_Collections_Generic_IEnumeratorGSystem_Int32C_System_Collections_Generic_IEnumerableGSystem_Int32C_GetEnumeratorFN)(System_Collections_Generic_IEnumerableGSystem_Int32C*);
    System_Object* (*System_Object_System_Collections_Generic_IEnumerableGSystem_Int32C__dynifaceFSystem_TypeN)(System_Collections_Generic_IEnumerableGSystem_Int32C*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_ICollectionGSystem_Int32C
#define VTBL__System_Collections_Generic_ICollectionGSystem_Int32C
struct System_Collections_Generic_ICollectionGSystem_Int32C__vtbl {
    System_Collections_Generic_IEnumerableGSystem_Int32C__vtbl ifce_System_Collections_Generic_IEnumerableGSystem_Int32C;
    Int32 (*Int32_System_Collections_Generic_ICollectionGSystem_Int32C_get_CountFN)(System_Collections_Generic_ICollectionGSystem_Int32C*);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_Int32C_get_IsReadOnlyFN)(System_Collections_Generic_ICollectionGSystem_Int32C*);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_Int32C_AddFInt32N)(System_Collections_Generic_ICollectionGSystem_Int32C*, Int32);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_Int32C_ClearFN)(System_Collections_Generic_ICollectionGSystem_Int32C*);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_Int32C_ContainsFInt32N)(System_Collections_Generic_ICollectionGSystem_Int32C*, Int32);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_Int32C_CopyToFInt32AY__Int32N)(System_Collections_Generic_ICollectionGSystem_Int32C*, System_Int32AY*, Int32);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_Int32C_RemoveFInt32N)(System_Collections_Generic_ICollectionGSystem_Int32C*, Int32);
    System_Object* (*System_Object_System_Collections_Generic_ICollectionGSystem_Int32C__dynifaceFSystem_TypeN)(System_Collections_Generic_ICollectionGSystem_Int32C*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IListGSystem_Int32C
#define VTBL__System_Collections_Generic_IListGSystem_Int32C
struct System_Collections_Generic_IListGSystem_Int32C__vtbl {
    System_Collections_Generic_ICollectionGSystem_Int32C__vtbl ifce_System_Collections_Generic_ICollectionGSystem_Int32C;
    Int32 (*Int32_System_Collections_Generic_IListGSystem_Int32C_get_ItemFInt32N)(System_Collections_Generic_IListGSystem_Int32C*, Int32);
    Void (*Void_System_Collections_Generic_IListGSystem_Int32C_set_ItemFInt32__Int32N)(System_Collections_Generic_IListGSystem_Int32C*, Int32, Int32);
    Int32 (*Int32_System_Collections_Generic_IListGSystem_Int32C_IndexOfFInt32N)(System_Collections_Generic_IListGSystem_Int32C*, Int32);
    Void (*Void_System_Collections_Generic_IListGSystem_Int32C_InsertFInt32__Int32N)(System_Collections_Generic_IListGSystem_Int32C*, Int32, Int32);
    Void (*Void_System_Collections_Generic_IListGSystem_Int32C_RemoveAtFInt32N)(System_Collections_Generic_IListGSystem_Int32C*, Int32);
    System_Object* (*System_Object_System_Collections_Generic_IListGSystem_Int32C__dynifaceFSystem_TypeN)(System_Collections_Generic_IListGSystem_Int32C*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C
#define VTBL__System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C
struct System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C__vtbl {
    System_Collections_Generic_IEnumerableGSystem_Int32C__vtbl ifce_System_Collections_Generic_IEnumerableGSystem_Int32C;
    Int32 (*Int32_System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C_get_CountFN)(System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C*);
    System_Object* (*System_Object_System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C__dynifaceFSystem_TypeN)(System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IReadOnlyListGSystem_Int32C
#define VTBL__System_Collections_Generic_IReadOnlyListGSystem_Int32C
struct System_Collections_Generic_IReadOnlyListGSystem_Int32C__vtbl {
    System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C__vtbl ifce_System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C;
    Int32 (*Int32_System_Collections_Generic_IReadOnlyListGSystem_Int32C_get_ItemFInt32N)(System_Collections_Generic_IReadOnlyListGSystem_Int32C*, Int32);
    System_Object* (*System_Object_System_Collections_Generic_IReadOnlyListGSystem_Int32C__dynifaceFSystem_TypeN)(System_Collections_Generic_IReadOnlyListGSystem_Int32C*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IEnumerableGSystem_ByteC
#define VTBL__System_Collections_Generic_IEnumerableGSystem_ByteC
struct System_Collections_Generic_IEnumerableGSystem_ByteC__vtbl {
    System_Collections_IEnumerable__vtbl ifce_System_Collections_IEnumerable;
    System_Collections_Generic_IEnumeratorGSystem_ByteC* (*System_Collections_Generic_IEnumeratorGSystem_ByteC_System_Collections_Generic_IEnumerableGSystem_ByteC_GetEnumeratorFN)(System_Collections_Generic_IEnumerableGSystem_ByteC*);
    System_Object* (*System_Object_System_Collections_Generic_IEnumerableGSystem_ByteC__dynifaceFSystem_TypeN)(System_Collections_Generic_IEnumerableGSystem_ByteC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_ICollectionGSystem_ByteC
#define VTBL__System_Collections_Generic_ICollectionGSystem_ByteC
struct System_Collections_Generic_ICollectionGSystem_ByteC__vtbl {
    System_Collections_Generic_IEnumerableGSystem_ByteC__vtbl ifce_System_Collections_Generic_IEnumerableGSystem_ByteC;
    Int32 (*Int32_System_Collections_Generic_ICollectionGSystem_ByteC_get_CountFN)(System_Collections_Generic_ICollectionGSystem_ByteC*);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_ByteC_get_IsReadOnlyFN)(System_Collections_Generic_ICollectionGSystem_ByteC*);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_ByteC_AddFByteN)(System_Collections_Generic_ICollectionGSystem_ByteC*, Byte);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_ByteC_ClearFN)(System_Collections_Generic_ICollectionGSystem_ByteC*);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_ByteC_ContainsFByteN)(System_Collections_Generic_ICollectionGSystem_ByteC*, Byte);
    Void (*Void_System_Collections_Generic_ICollectionGSystem_ByteC_CopyToFByteAY__Int32N)(System_Collections_Generic_ICollectionGSystem_ByteC*, System_ByteAY*, Int32);
    Boolean (*Boolean_System_Collections_Generic_ICollectionGSystem_ByteC_RemoveFByteN)(System_Collections_Generic_ICollectionGSystem_ByteC*, Byte);
    System_Object* (*System_Object_System_Collections_Generic_ICollectionGSystem_ByteC__dynifaceFSystem_TypeN)(System_Collections_Generic_ICollectionGSystem_ByteC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IListGSystem_ByteC
#define VTBL__System_Collections_Generic_IListGSystem_ByteC
struct System_Collections_Generic_IListGSystem_ByteC__vtbl {
    System_Collections_Generic_ICollectionGSystem_ByteC__vtbl ifce_System_Collections_Generic_ICollectionGSystem_ByteC;
    Byte (*Byte_System_Collections_Generic_IListGSystem_ByteC_get_ItemFInt32N)(System_Collections_Generic_IListGSystem_ByteC*, Int32);
    Void (*Void_System_Collections_Generic_IListGSystem_ByteC_set_ItemFInt32__ByteN)(System_Collections_Generic_IListGSystem_ByteC*, Int32, Byte);
    Int32 (*Int32_System_Collections_Generic_IListGSystem_ByteC_IndexOfFByteN)(System_Collections_Generic_IListGSystem_ByteC*, Byte);
    Void (*Void_System_Collections_Generic_IListGSystem_ByteC_InsertFInt32__ByteN)(System_Collections_Generic_IListGSystem_ByteC*, Int32, Byte);
    Void (*Void_System_Collections_Generic_IListGSystem_ByteC_RemoveAtFInt32N)(System_Collections_Generic_IListGSystem_ByteC*, Int32);
    System_Object* (*System_Object_System_Collections_Generic_IListGSystem_ByteC__dynifaceFSystem_TypeN)(System_Collections_Generic_IListGSystem_ByteC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC
#define VTBL__System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC
struct System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC__vtbl {
    System_Collections_Generic_IEnumerableGSystem_ByteC__vtbl ifce_System_Collections_Generic_IEnumerableGSystem_ByteC;
    Int32 (*Int32_System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC_get_CountFN)(System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC*);
    System_Object* (*System_Object_System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC__dynifaceFSystem_TypeN)(System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IReadOnlyListGSystem_ByteC
#define VTBL__System_Collections_Generic_IReadOnlyListGSystem_ByteC
struct System_Collections_Generic_IReadOnlyListGSystem_ByteC__vtbl {
    System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC__vtbl ifce_System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC;
    Byte (*Byte_System_Collections_Generic_IReadOnlyListGSystem_ByteC_get_ItemFInt32N)(System_Collections_Generic_IReadOnlyListGSystem_ByteC*, Int32);
    System_Object* (*System_Object_System_Collections_Generic_IReadOnlyListGSystem_ByteC__dynifaceFSystem_TypeN)(System_Collections_Generic_IReadOnlyListGSystem_ByteC*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IEnumeratorGSystem_Int32C
#define VTBL__System_Collections_Generic_IEnumeratorGSystem_Int32C
struct System_Collections_Generic_IEnumeratorGSystem_Int32C__vtbl {
    System_IDisposable__vtbl ifce_System_IDisposable;
    System_Collections_IEnumerator__vtbl ifce_System_Collections_IEnumerator;
    Int32 (*Int32_System_Collections_Generic_IEnumeratorGSystem_Int32C_get_CurrentFN)(System_Collections_Generic_IEnumeratorGSystem_Int32C*);
    System_Object* (*System_Object_System_Collections_Generic_IEnumeratorGSystem_Int32C__dynifaceFSystem_TypeN)(System_Collections_Generic_IEnumeratorGSystem_Int32C*, System_Type*);
};
#endif
#ifndef VTBL__System_Collections_Generic_IEnumeratorGSystem_ByteC
#define VTBL__System_Collections_Generic_IEnumeratorGSystem_ByteC
struct System_Collections_Generic_IEnumeratorGSystem_ByteC__vtbl {
    System_IDisposable__vtbl ifce_System_IDisposable;
    System_Collections_IEnumerator__vtbl ifce_System_Collections_IEnumerator;
    Byte (*Byte_System_Collections_Generic_IEnumeratorGSystem_ByteC_get_CurrentFN)(System_Collections_Generic_IEnumeratorGSystem_ByteC*);
    System_Object* (*System_Object_System_Collections_Generic_IEnumeratorGSystem_ByteC__dynifaceFSystem_TypeN)(System_Collections_Generic_IEnumeratorGSystem_ByteC*, System_Type*);
};
#endif

struct HelloWorld {
    System_Object base;
};
Void Void_HelloWorld__ctorFN(HelloWorld* __this);
Int32 Int32_HelloWorld_MainFSystem_StringAYN(System_StringAY* args);
HelloWorld* HelloWorld_HelloWorld__newFN();
Void Void_HelloWorld__initFN(HelloWorld* __this);
Int32 Int32_HelloWorld__getsizeFN(HelloWorld* __this);
System_Type* System_Type_HelloWorld__gettypeFN(HelloWorld* __this);
System_Object* System_Object_HelloWorld__dynifaceFSystem_TypeN(HelloWorld* __this, System_Type* _type);
System_Type* System_Type_HelloWorld__sgettypeFN();

#ifndef D__System_Collections_Generic_IEnumerableGSystem_StringC
#define D__System_Collections_Generic_IEnumerableGSystem_StringC
struct System_Collections_Generic_IEnumerableGSystem_StringC {
    System_Collections_Generic_IEnumerableGSystem_StringC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IEnumerableGSystem_StringC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_ICollectionGSystem_StringC
#define D__System_Collections_Generic_ICollectionGSystem_StringC
struct System_Collections_Generic_ICollectionGSystem_StringC {
    System_Collections_Generic_ICollectionGSystem_StringC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_ICollectionGSystem_StringC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IListGSystem_StringC
#define D__System_Collections_Generic_IListGSystem_StringC
struct System_Collections_Generic_IListGSystem_StringC {
    System_Collections_Generic_IListGSystem_StringC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IListGSystem_StringC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IReadOnlyCollectionGSystem_StringC
#define D__System_Collections_Generic_IReadOnlyCollectionGSystem_StringC
struct System_Collections_Generic_IReadOnlyCollectionGSystem_StringC {
    System_Collections_Generic_IReadOnlyCollectionGSystem_StringC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IReadOnlyCollectionGSystem_StringC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IReadOnlyListGSystem_StringC
#define D__System_Collections_Generic_IReadOnlyListGSystem_StringC
struct System_Collections_Generic_IReadOnlyListGSystem_StringC {
    System_Collections_Generic_IReadOnlyListGSystem_StringC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IReadOnlyListGSystem_StringC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_StringAY
#define D__System_StringAY
struct System_StringAY {
    System_Array base;
    Int16 rank;
    Int16 typeCode;
    Int32 elementSize;
    Int32 length;
    System_String* data[0];
};
#endif
Void Void_System_StringAY__ctorFInt32N_HelloWorld_r00iaxum_dll(System_StringAY* __this, Int32 param0);
System_StringAY* System_StringAY_System_StringAY__newFInt32N_HelloWorld_r00iaxum_dll(Int32 param0);
Void Void_System_StringAY__initFN_HelloWorld_r00iaxum_dll(System_StringAY* __this);
Int32 Int32_System_StringAY__getsizeFN_HelloWorld_r00iaxum_dll(System_StringAY* __this);
System_Type* System_Type_System_StringAY__gettypeFN_HelloWorld_r00iaxum_dll(System_StringAY* __this);
System_Object* System_Object_System_StringAY__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_StringAY* __this, System_Type* _type);
System_Type* System_Type_System_StringAY__sgettypeFN_HelloWorld_r00iaxum_dll();
System_Collections_Generic_IEnumeratorGSystem_StringC* System_Collections_Generic_IEnumeratorGSystem_StringC_System_StringAY_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_StringAY* __this);
Int32 Int32_System_StringAY_get_CountFN_HelloWorld_r00iaxum_dll(System_StringAY* __this);
System_String* System_String_System_StringAY_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_StringAY* __this, Int32 index);
Void Void_System_StringAY_set_ItemFInt32__System_StringN_HelloWorld_r00iaxum_dll(System_StringAY* __this, Int32 index, System_String* _value);
Void Void_System_StringAY_CopyToFSystem_StringAY__Int32N_HelloWorld_r00iaxum_dll(System_StringAY* __this, System_StringAY* _array, Int32 arrayIndex);

#ifndef D__System_ArraySegmentGSystem_StringC
#define D__System_ArraySegmentGSystem_StringC
struct System_ArraySegmentGSystem_StringC__struct_data {
    System_StringAY* _array;
    Int32 _offset;
    Int32 _count;
};
#endif

#ifndef DC__System_ArraySegmentGSystem_StringC
#define DC__System_ArraySegmentGSystem_StringC
struct System_ArraySegmentGSystem_StringC {
    System_ValueType base;
    System_StringAY* _array;
    Int32 _offset;
    Int32 _count;
};
#endif
Void Void_System_ArraySegmentGSystem_StringC__ctorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
Void Void_System_ArraySegmentGSystem_StringC__ctorFSystem_StringAYN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_StringAY* array);
Void Void_System_ArraySegmentGSystem_StringC__ctorFSystem_StringAY__Int32__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_StringAY* array, Int32 offset, Int32 count);
System_StringAY* System_StringAY_System_ArraySegmentGSystem_StringC_get_ArrayFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC_get_OffsetFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC_get_CountFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC_GetHashCodeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
Boolean Boolean_System_ArraySegmentGSystem_StringC_EqualsFSystem_ObjectN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_Object* obj);
Boolean Boolean_System_ArraySegmentGSystem_StringC_EqualsFSystem_ArraySegmentGSystem_StringCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_ArraySegmentGSystem_StringC__struct_data obj);
Boolean Boolean_System_ArraySegmentGSystem_StringC_op_EqualityFSystem_ArraySegmentGSystem_StringC__System_ArraySegmentGSystem_StringCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data a, System_ArraySegmentGSystem_StringC__struct_data b);
Boolean Boolean_System_ArraySegmentGSystem_StringC_op_InequalityFSystem_ArraySegmentGSystem_StringC__System_ArraySegmentGSystem_StringCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data a, System_ArraySegmentGSystem_StringC__struct_data b);
System_String* System_String_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, Int32 index);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_set_ItemFInt32__System_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, Int32 index, System_String* value);
Int32 Int32_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_IndexOfFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_InsertFInt32__System_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, Int32 index, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_RemoveAtFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, Int32 index);
System_String* System_String_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IReadOnlyListGSystem_StringC_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, Int32 index);
Boolean Boolean_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_get_IsReadOnlyFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_AddFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_ClearFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
Boolean Boolean_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_ContainsFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_CopyToFSystem_StringAY__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_StringAY* array, Int32 arrayIndex);
Boolean Boolean_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_RemoveFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this, System_String* item);
System_Collections_Generic_IEnumeratorGSystem_StringC* System_Collections_Generic_IEnumeratorGSystem_StringC_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IEnumerableGSystem_StringC_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
System_Collections_IEnumerator* System_Collections_IEnumerator_System_ArraySegmentGSystem_StringC_System_Collections_IEnumerable_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data* __this);
System_ArraySegmentGSystem_StringC* System_ArraySegmentGSystem_StringC_System_ArraySegmentGSystem_StringC__newFN_HelloWorld_r00iaxum_dll();
Void Void_System_ArraySegmentGSystem_StringC__initFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC__getsizeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
System_Type* System_Type_System_ArraySegmentGSystem_StringC__gettypeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
System_Object* System_Object_System_ArraySegmentGSystem_StringC__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_Type* _type);
System_Type* System_Type_System_ArraySegmentGSystem_StringC__sgettypeFN_HelloWorld_r00iaxum_dll();
System_ArraySegmentGSystem_StringC* System_ArraySegmentGSystem_StringC_System_ArraySegmentGSystem_StringC__boxFSystem_ArraySegmentGSystem_StringCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC__struct_data _value);
System_ArraySegmentGSystem_StringC__struct_data System_ArraySegmentGSystem_StringC_System_ArraySegmentGSystem_StringC__unboxFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
System_StringAY* System_StringAY_System_ArraySegmentGSystem_StringC_get_Array__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC_get_Offset__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC_get_Count__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC_GetHashCode__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
Boolean Boolean_System_ArraySegmentGSystem_StringC_Equals__entry_for_objectFSystem_ObjectN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_Object* obj);
Boolean Boolean_System_ArraySegmentGSystem_StringC_Equals__entry_for_objectFSystem_ArraySegmentGSystem_StringCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_ArraySegmentGSystem_StringC__struct_data obj);
System_String* System_String_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_get_Item__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, Int32 index);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_set_Item__entry_for_objectFInt32__System_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, Int32 index, System_String* value);
Int32 Int32_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_IndexOf__entry_for_objectFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_Insert__entry_for_objectFInt32__System_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, Int32 index, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IListGSystem_StringC_RemoveAt__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, Int32 index);
System_String* System_String_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IReadOnlyListGSystem_StringC_get_Item__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, Int32 index);
Boolean Boolean_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_get_IsReadOnly__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_Add__entry_for_objectFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_Clear__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
Boolean Boolean_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_Contains__entry_for_objectFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_String* item);
Void Void_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_CopyTo__entry_for_objectFSystem_StringAY__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_StringAY* array, Int32 arrayIndex);
Boolean Boolean_System_ArraySegmentGSystem_StringC_System_Collections_Generic_ICollectionGSystem_StringC_Remove__entry_for_objectFSystem_StringN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this, System_String* item);
System_Collections_Generic_IEnumeratorGSystem_StringC* System_Collections_Generic_IEnumeratorGSystem_StringC_System_ArraySegmentGSystem_StringC_System_Collections_Generic_IEnumerableGSystem_StringC_GetEnumerator__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);
System_Collections_IEnumerator* System_Collections_IEnumerator_System_ArraySegmentGSystem_StringC_System_Collections_IEnumerable_GetEnumerator__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC* __this);

#ifndef D__System_Collections_Generic_IEnumeratorGSystem_StringC
#define D__System_Collections_Generic_IEnumeratorGSystem_StringC
struct System_Collections_Generic_IEnumeratorGSystem_StringC {
    System_Collections_Generic_IEnumeratorGSystem_StringC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IEnumeratorGSystem_StringC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator
#define D__System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator
struct System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator {
    System_Object base;
    System_StringAY* _array;
    Int32 _start;
    Int32 _end;
    Int32 _current;
};
#endif
Void Void_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__ctorFSystem_ArraySegmentGSystem_StringCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this, System_ArraySegmentGSystem_StringC__struct_data arraySegment);
Boolean Boolean_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_MoveNextFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
System_String* System_String_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_get_CurrentFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
System_Object* System_Object_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_System_Collections_IEnumerator_get_CurrentFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
Void Void_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_System_Collections_IEnumerator_ResetFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
Void Void_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_DisposeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__newFN_HelloWorld_r00iaxum_dll();
Void Void_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__initFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
Int32 Int32_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__getsizeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
System_Type* System_Type_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__gettypeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this);
System_Object* System_Object_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator* __this, System_Type* _type);
System_Type* System_Type_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IEnumerableGSystem_Int32C
#define D__System_Collections_Generic_IEnumerableGSystem_Int32C
struct System_Collections_Generic_IEnumerableGSystem_Int32C {
    System_Collections_Generic_IEnumerableGSystem_Int32C__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IEnumerableGSystem_Int32C__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_ICollectionGSystem_Int32C
#define D__System_Collections_Generic_ICollectionGSystem_Int32C
struct System_Collections_Generic_ICollectionGSystem_Int32C {
    System_Collections_Generic_ICollectionGSystem_Int32C__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_ICollectionGSystem_Int32C__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IListGSystem_Int32C
#define D__System_Collections_Generic_IListGSystem_Int32C
struct System_Collections_Generic_IListGSystem_Int32C {
    System_Collections_Generic_IListGSystem_Int32C__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IListGSystem_Int32C__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C
#define D__System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C
struct System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C {
    System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IReadOnlyListGSystem_Int32C
#define D__System_Collections_Generic_IReadOnlyListGSystem_Int32C
struct System_Collections_Generic_IReadOnlyListGSystem_Int32C {
    System_Collections_Generic_IReadOnlyListGSystem_Int32C__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IReadOnlyListGSystem_Int32C__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Int32AY
#define D__System_Int32AY
struct System_Int32AY {
    System_Array base;
    Int16 rank;
    Int16 typeCode;
    Int32 elementSize;
    Int32 length;
    Int32 data[0];
};
#endif
Void Void_System_Int32AY__ctorFInt32N_HelloWorld_r00iaxum_dll(System_Int32AY* __this, Int32 param0);
System_Int32AY* Int32AY_System_Int32AY__newFInt32N_HelloWorld_r00iaxum_dll(Int32 param0);
Void Void_System_Int32AY__initFN_HelloWorld_r00iaxum_dll(System_Int32AY* __this);
Int32 Int32_System_Int32AY__getsizeFN_HelloWorld_r00iaxum_dll(System_Int32AY* __this);
System_Type* System_Type_System_Int32AY__gettypeFN_HelloWorld_r00iaxum_dll(System_Int32AY* __this);
System_Object* System_Object_System_Int32AY__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_Int32AY* __this, System_Type* _type);
System_Type* System_Type_System_Int32AY__sgettypeFN_HelloWorld_r00iaxum_dll();
System_Collections_Generic_IEnumeratorGSystem_Int32C* System_Collections_Generic_IEnumeratorGSystem_Int32C_System_Int32AY_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_Int32AY* __this);
Int32 Int32_System_Int32AY_get_CountFN_HelloWorld_r00iaxum_dll(System_Int32AY* __this);
Int32 Int32_System_Int32AY_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_Int32AY* __this, Int32 index);
Void Void_System_Int32AY_set_ItemFInt32__Int32N_HelloWorld_r00iaxum_dll(System_Int32AY* __this, Int32 index, Int32 _value);
Void Void_System_Int32AY_CopyToFInt32AY__Int32N_HelloWorld_r00iaxum_dll(System_Int32AY* __this, System_Int32AY* _array, Int32 arrayIndex);

#ifndef D__System_Collections_Generic_IEnumerableGSystem_ByteC
#define D__System_Collections_Generic_IEnumerableGSystem_ByteC
struct System_Collections_Generic_IEnumerableGSystem_ByteC {
    System_Collections_Generic_IEnumerableGSystem_ByteC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IEnumerableGSystem_ByteC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_ICollectionGSystem_ByteC
#define D__System_Collections_Generic_ICollectionGSystem_ByteC
struct System_Collections_Generic_ICollectionGSystem_ByteC {
    System_Collections_Generic_ICollectionGSystem_ByteC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_ICollectionGSystem_ByteC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IListGSystem_ByteC
#define D__System_Collections_Generic_IListGSystem_ByteC
struct System_Collections_Generic_IListGSystem_ByteC {
    System_Collections_Generic_IListGSystem_ByteC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IListGSystem_ByteC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC
#define D__System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC
struct System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC {
    System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_Collections_Generic_IReadOnlyListGSystem_ByteC
#define D__System_Collections_Generic_IReadOnlyListGSystem_ByteC
struct System_Collections_Generic_IReadOnlyListGSystem_ByteC {
    System_Collections_Generic_IReadOnlyListGSystem_ByteC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IReadOnlyListGSystem_ByteC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_ByteAY
#define D__System_ByteAY
struct System_ByteAY {
    System_Array base;
    Int16 rank;
    Int16 typeCode;
    Int32 elementSize;
    Int32 length;
    Byte data[0];
};
#endif
Void Void_System_ByteAY__ctorFInt32N_HelloWorld_r00iaxum_dll(System_ByteAY* __this, Int32 param0);
System_ByteAY* ByteAY_System_ByteAY__newFInt32N_HelloWorld_r00iaxum_dll(Int32 param0);
Void Void_System_ByteAY__initFN_HelloWorld_r00iaxum_dll(System_ByteAY* __this);
Int32 Int32_System_ByteAY__getsizeFN_HelloWorld_r00iaxum_dll(System_ByteAY* __this);
System_Type* System_Type_System_ByteAY__gettypeFN_HelloWorld_r00iaxum_dll(System_ByteAY* __this);
System_Object* System_Object_System_ByteAY__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_ByteAY* __this, System_Type* _type);
System_Type* System_Type_System_ByteAY__sgettypeFN_HelloWorld_r00iaxum_dll();
System_Collections_Generic_IEnumeratorGSystem_ByteC* System_Collections_Generic_IEnumeratorGSystem_ByteC_System_ByteAY_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_ByteAY* __this);
Int32 Int32_System_ByteAY_get_CountFN_HelloWorld_r00iaxum_dll(System_ByteAY* __this);
Byte Byte_System_ByteAY_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_ByteAY* __this, Int32 index);
Void Void_System_ByteAY_set_ItemFInt32__ByteN_HelloWorld_r00iaxum_dll(System_ByteAY* __this, Int32 index, Byte _value);
Void Void_System_ByteAY_CopyToFByteAY__Int32N_HelloWorld_r00iaxum_dll(System_ByteAY* __this, System_ByteAY* _array, Int32 arrayIndex);

#ifndef D__System_ArraySegmentGSystem_Int32C
#define D__System_ArraySegmentGSystem_Int32C
struct System_ArraySegmentGSystem_Int32C__struct_data {
    System_Int32AY* _array;
    Int32 _offset;
    Int32 _count;
};
#endif

#ifndef DC__System_ArraySegmentGSystem_Int32C
#define DC__System_ArraySegmentGSystem_Int32C
struct System_ArraySegmentGSystem_Int32C {
    System_ValueType base;
    System_Int32AY* _array;
    Int32 _offset;
    Int32 _count;
};
#endif
Void Void_System_ArraySegmentGSystem_Int32C__ctorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
Void Void_System_ArraySegmentGSystem_Int32C__ctorFInt32AYN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, System_Int32AY* array);
Void Void_System_ArraySegmentGSystem_Int32C__ctorFInt32AY__Int32__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, System_Int32AY* array, Int32 offset, Int32 count);
System_Int32AY* Int32AY_System_ArraySegmentGSystem_Int32C_get_ArrayFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_get_OffsetFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_get_CountFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_GetHashCodeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_EqualsFSystem_ObjectN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, System_Object* obj);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_EqualsFSystem_ArraySegmentGSystem_Int32CN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, System_ArraySegmentGSystem_Int32C__struct_data obj);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_op_EqualityFSystem_ArraySegmentGSystem_Int32C__System_ArraySegmentGSystem_Int32CN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data a, System_ArraySegmentGSystem_Int32C__struct_data b);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_op_InequalityFSystem_ArraySegmentGSystem_Int32C__System_ArraySegmentGSystem_Int32CN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data a, System_ArraySegmentGSystem_Int32C__struct_data b);
Int32 Int32_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 index);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_set_ItemFInt32__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 index, Int32 value);
Int32 Int32_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_IndexOfFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_InsertFInt32__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 index, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_RemoveAtFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 index);
Int32 Int32_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IReadOnlyListGSystem_Int32C_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 index);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_get_IsReadOnlyFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_AddFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_ClearFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_ContainsFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_CopyToFInt32AY__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, System_Int32AY* array, Int32 arrayIndex);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_RemoveFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this, Int32 item);
System_Collections_Generic_IEnumeratorGSystem_Int32C* System_Collections_Generic_IEnumeratorGSystem_Int32C_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IEnumerableGSystem_Int32C_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
System_Collections_IEnumerator* System_Collections_IEnumerator_System_ArraySegmentGSystem_Int32C_System_Collections_IEnumerable_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data* __this);
System_ArraySegmentGSystem_Int32C* System_ArraySegmentGSystem_Int32C_System_ArraySegmentGSystem_Int32C__newFN_HelloWorld_r00iaxum_dll();
Void Void_System_ArraySegmentGSystem_Int32C__initFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C__getsizeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
System_Type* System_Type_System_ArraySegmentGSystem_Int32C__gettypeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
System_Object* System_Object_System_ArraySegmentGSystem_Int32C__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, System_Type* _type);
System_Type* System_Type_System_ArraySegmentGSystem_Int32C__sgettypeFN_HelloWorld_r00iaxum_dll();
System_ArraySegmentGSystem_Int32C* System_ArraySegmentGSystem_Int32C_System_ArraySegmentGSystem_Int32C__boxFSystem_ArraySegmentGSystem_Int32CN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C__struct_data _value);
System_ArraySegmentGSystem_Int32C__struct_data System_ArraySegmentGSystem_Int32C_System_ArraySegmentGSystem_Int32C__unboxFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
System_Int32AY* Int32AY_System_ArraySegmentGSystem_Int32C_get_Array__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_get_Offset__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_get_Count__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_GetHashCode__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_Equals__entry_for_objectFSystem_ObjectN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, System_Object* obj);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_Equals__entry_for_objectFSystem_ArraySegmentGSystem_Int32CN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, System_ArraySegmentGSystem_Int32C__struct_data obj);
Int32 Int32_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_get_Item__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 index);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_set_Item__entry_for_objectFInt32__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 index, Int32 value);
Int32 Int32_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_IndexOf__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_Insert__entry_for_objectFInt32__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 index, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IListGSystem_Int32C_RemoveAt__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 index);
Int32 Int32_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IReadOnlyListGSystem_Int32C_get_Item__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 index);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_get_IsReadOnly__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_Add__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_Clear__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_Contains__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 item);
Void Void_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_CopyTo__entry_for_objectFInt32AY__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, System_Int32AY* array, Int32 arrayIndex);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_ICollectionGSystem_Int32C_Remove__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this, Int32 item);
System_Collections_Generic_IEnumeratorGSystem_Int32C* System_Collections_Generic_IEnumeratorGSystem_Int32C_System_ArraySegmentGSystem_Int32C_System_Collections_Generic_IEnumerableGSystem_Int32C_GetEnumerator__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);
System_Collections_IEnumerator* System_Collections_IEnumerator_System_ArraySegmentGSystem_Int32C_System_Collections_IEnumerable_GetEnumerator__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C* __this);

#ifndef D__System_Collections_Generic_IEnumeratorGSystem_Int32C
#define D__System_Collections_Generic_IEnumeratorGSystem_Int32C
struct System_Collections_Generic_IEnumeratorGSystem_Int32C {
    System_Collections_Generic_IEnumeratorGSystem_Int32C__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IEnumeratorGSystem_Int32C__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator
#define D__System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator
struct System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator {
    System_Object base;
    System_Int32AY* _array;
    Int32 _start;
    Int32 _end;
    Int32 _current;
};
#endif
Void Void_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__ctorFSystem_ArraySegmentGSystem_Int32CN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this, System_ArraySegmentGSystem_Int32C__struct_data arraySegment);
Boolean Boolean_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_MoveNextFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_get_CurrentFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
System_Object* System_Object_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_System_Collections_IEnumerator_get_CurrentFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
Void Void_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_System_Collections_IEnumerator_ResetFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
Void Void_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_DisposeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__newFN_HelloWorld_r00iaxum_dll();
Void Void_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__initFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
Int32 Int32_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__getsizeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
System_Type* System_Type_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__gettypeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this);
System_Object* System_Object_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator* __this, System_Type* _type);
System_Type* System_Type_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_ArraySegmentGSystem_ByteC
#define D__System_ArraySegmentGSystem_ByteC
struct System_ArraySegmentGSystem_ByteC__struct_data {
    System_ByteAY* _array;
    Int32 _offset;
    Int32 _count;
};
#endif

#ifndef DC__System_ArraySegmentGSystem_ByteC
#define DC__System_ArraySegmentGSystem_ByteC
struct System_ArraySegmentGSystem_ByteC {
    System_ValueType base;
    System_ByteAY* _array;
    Int32 _offset;
    Int32 _count;
};
#endif
Void Void_System_ArraySegmentGSystem_ByteC__ctorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
Void Void_System_ArraySegmentGSystem_ByteC__ctorFByteAYN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, System_ByteAY* array);
Void Void_System_ArraySegmentGSystem_ByteC__ctorFByteAY__Int32__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, System_ByteAY* array, Int32 offset, Int32 count);
System_ByteAY* ByteAY_System_ArraySegmentGSystem_ByteC_get_ArrayFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC_get_OffsetFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC_get_CountFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC_GetHashCodeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_EqualsFSystem_ObjectN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, System_Object* obj);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_EqualsFSystem_ArraySegmentGSystem_ByteCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, System_ArraySegmentGSystem_ByteC__struct_data obj);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_op_EqualityFSystem_ArraySegmentGSystem_ByteC__System_ArraySegmentGSystem_ByteCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data a, System_ArraySegmentGSystem_ByteC__struct_data b);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_op_InequalityFSystem_ArraySegmentGSystem_ByteC__System_ArraySegmentGSystem_ByteCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data a, System_ArraySegmentGSystem_ByteC__struct_data b);
Byte Byte_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Int32 index);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_set_ItemFInt32__ByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Int32 index, Byte value);
Int32 Int32_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_IndexOfFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_InsertFInt32__ByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Int32 index, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_RemoveAtFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Int32 index);
Byte Byte_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IReadOnlyListGSystem_ByteC_get_ItemFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Int32 index);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_get_IsReadOnlyFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_AddFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_ClearFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_ContainsFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_CopyToFByteAY__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, System_ByteAY* array, Int32 arrayIndex);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_RemoveFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this, Byte item);
System_Collections_Generic_IEnumeratorGSystem_ByteC* System_Collections_Generic_IEnumeratorGSystem_ByteC_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IEnumerableGSystem_ByteC_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
System_Collections_IEnumerator* System_Collections_IEnumerator_System_ArraySegmentGSystem_ByteC_System_Collections_IEnumerable_GetEnumeratorFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data* __this);
System_ArraySegmentGSystem_ByteC* System_ArraySegmentGSystem_ByteC_System_ArraySegmentGSystem_ByteC__newFN_HelloWorld_r00iaxum_dll();
Void Void_System_ArraySegmentGSystem_ByteC__initFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC__getsizeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
System_Type* System_Type_System_ArraySegmentGSystem_ByteC__gettypeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
System_Object* System_Object_System_ArraySegmentGSystem_ByteC__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, System_Type* _type);
System_Type* System_Type_System_ArraySegmentGSystem_ByteC__sgettypeFN_HelloWorld_r00iaxum_dll();
System_ArraySegmentGSystem_ByteC* System_ArraySegmentGSystem_ByteC_System_ArraySegmentGSystem_ByteC__boxFSystem_ArraySegmentGSystem_ByteCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC__struct_data _value);
System_ArraySegmentGSystem_ByteC__struct_data System_ArraySegmentGSystem_ByteC_System_ArraySegmentGSystem_ByteC__unboxFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
System_ByteAY* ByteAY_System_ArraySegmentGSystem_ByteC_get_Array__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC_get_Offset__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC_get_Count__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC_GetHashCode__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_Equals__entry_for_objectFSystem_ObjectN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, System_Object* obj);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_Equals__entry_for_objectFSystem_ArraySegmentGSystem_ByteCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, System_ArraySegmentGSystem_ByteC__struct_data obj);
Byte Byte_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_get_Item__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Int32 index);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_set_Item__entry_for_objectFInt32__ByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Int32 index, Byte value);
Int32 Int32_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_IndexOf__entry_for_objectFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_Insert__entry_for_objectFInt32__ByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Int32 index, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IListGSystem_ByteC_RemoveAt__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Int32 index);
Byte Byte_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IReadOnlyListGSystem_ByteC_get_Item__entry_for_objectFInt32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Int32 index);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_get_IsReadOnly__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_Add__entry_for_objectFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_Clear__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_Contains__entry_for_objectFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Byte item);
Void Void_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_CopyTo__entry_for_objectFByteAY__Int32N_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, System_ByteAY* array, Int32 arrayIndex);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_ICollectionGSystem_ByteC_Remove__entry_for_objectFByteN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this, Byte item);
System_Collections_Generic_IEnumeratorGSystem_ByteC* System_Collections_Generic_IEnumeratorGSystem_ByteC_System_ArraySegmentGSystem_ByteC_System_Collections_Generic_IEnumerableGSystem_ByteC_GetEnumerator__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);
System_Collections_IEnumerator* System_Collections_IEnumerator_System_ArraySegmentGSystem_ByteC_System_Collections_IEnumerable_GetEnumerator__entry_for_objectFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC* __this);

#ifndef D__System_Collections_Generic_IEnumeratorGSystem_ByteC
#define D__System_Collections_Generic_IEnumeratorGSystem_ByteC
struct System_Collections_Generic_IEnumeratorGSystem_ByteC {
    System_Collections_Generic_IEnumeratorGSystem_ByteC__vtbl* __vtbl;
    Void* __this;
};
#endif
System_Type* System_Type_System_Collections_Generic_IEnumeratorGSystem_ByteC__sgettypeFN_HelloWorld_r00iaxum_dll();

#ifndef D__System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator
#define D__System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator
struct System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator {
    System_Object base;
    System_ByteAY* _array;
    Int32 _start;
    Int32 _end;
    Int32 _current;
};
#endif
Void Void_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__ctorFSystem_ArraySegmentGSystem_ByteCN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this, System_ArraySegmentGSystem_ByteC__struct_data arraySegment);
Boolean Boolean_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_MoveNextFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
Byte Byte_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_get_CurrentFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
System_Object* System_Object_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_System_Collections_IEnumerator_get_CurrentFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
Void Void_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_System_Collections_IEnumerator_ResetFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
Void Void_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_DisposeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__newFN_HelloWorld_r00iaxum_dll();
Void Void_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__initFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
Int32 Int32_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__getsizeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
System_Type* System_Type_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__gettypeFN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this);
System_Object* System_Object_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__dynifaceFSystem_TypeN_HelloWorld_r00iaxum_dll(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator* __this, System_Type* _type);
System_Type* System_Type_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__sgettypeFN_HelloWorld_r00iaxum_dll();
extern System_Type* HelloWorld__type;
extern const Void* HelloWorld_vtable_impl[];
struct HelloWorld__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_Object_EqualsFSystem_ObjectN)(System_Object*, System_Object*);
    Int32 (*Int32_System_Object_GetHashCodeFN)(System_Object*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_HelloWorld__getsizeFN)(HelloWorld*);
    System_Type* (*System_Type_HelloWorld__gettypeFN)(HelloWorld*);
    System_Object* (*System_Object_HelloWorld__dynifaceFSystem_TypeN)(HelloWorld*, System_Type*);
};
extern System_Type* System_Collections_Generic_IEnumerableGSystem_StringC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_ICollectionGSystem_StringC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IListGSystem_StringC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IReadOnlyCollectionGSystem_StringC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IReadOnlyListGSystem_StringC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_StringAY__type_HelloWorld_r00iaxum_dll;
extern const Void* System_StringAY_vtable_System_Collections_Generic_IListGSystem_StringC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_StringAY_vtable_System_Collections_Generic_IReadOnlyListGSystem_StringC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_StringAY_vtable_System_ICloneable_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_StringAY_vtable_System_Collections_IList_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_StringAY_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_StringAY
#define VTBL__System_StringAY
struct System_StringAY__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_Object_EqualsFSystem_ObjectN)(System_Object*, System_Object*);
    Int32 (*Int32_System_Object_GetHashCodeFN)(System_Object*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_StringAY__getsizeFN)(System_StringAY*);
    System_Type* (*System_Type_System_StringAY__gettypeFN)(System_StringAY*);
    System_Object* (*System_Object_System_StringAY__dynifaceFSystem_TypeN)(System_StringAY*, System_Type*);
    System_ICloneable__vtbl* ifce_System_ICloneable;
    System_Collections_IList__vtbl* ifce_System_Collections_IList;
    System_Collections_Generic_IListGSystem_StringC__vtbl* ifce_System_Collections_Generic_IListGSystem_StringC;
    System_Collections_Generic_IReadOnlyListGSystem_StringC__vtbl* ifce_System_Collections_Generic_IReadOnlyListGSystem_StringC;
};
#endif
extern System_Type* System_ArraySegmentGSystem_StringC__type_HelloWorld_r00iaxum_dll;
extern const Void* System_ArraySegmentGSystem_StringC_vtable_System_Collections_Generic_IListGSystem_StringC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_StringC_vtable_System_Collections_Generic_IReadOnlyListGSystem_StringC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_StringC_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_ArraySegmentGSystem_StringC
#define VTBL__System_ArraySegmentGSystem_StringC
struct System_ArraySegmentGSystem_StringC__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_ArraySegmentGSystem_StringC_EqualsFSystem_ObjectN)(System_ArraySegmentGSystem_StringC*, System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_StringC_GetHashCodeFN)(System_ArraySegmentGSystem_StringC*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_StringC__getsizeFN)(System_ArraySegmentGSystem_StringC*);
    System_Type* (*System_Type_System_ArraySegmentGSystem_StringC__gettypeFN)(System_ArraySegmentGSystem_StringC*);
    System_Object* (*System_Object_System_ArraySegmentGSystem_StringC__dynifaceFSystem_TypeN)(System_ArraySegmentGSystem_StringC*, System_Type*);
    System_Collections_Generic_IListGSystem_StringC__vtbl* ifce_System_Collections_Generic_IListGSystem_StringC;
    System_Collections_Generic_IReadOnlyListGSystem_StringC__vtbl* ifce_System_Collections_Generic_IReadOnlyListGSystem_StringC;
};
#endif
extern System_Type* System_Collections_Generic_IEnumeratorGSystem_StringC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__type_HelloWorld_r00iaxum_dll;
extern const Void* System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_vtable_System_Collections_Generic_IEnumeratorGSystem_StringC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator
#define VTBL__System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator
struct System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_Object_EqualsFSystem_ObjectN)(System_Object*, System_Object*);
    Int32 (*Int32_System_Object_GetHashCodeFN)(System_Object*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__getsizeFN)(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator*);
    System_Type* (*System_Type_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__gettypeFN)(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator*);
    System_Object* (*System_Object_System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator__dynifaceFSystem_TypeN)(System_ArraySegmentGSystem_StringC_ArraySegmentEnumerator*, System_Type*);
    System_Collections_Generic_IEnumeratorGSystem_StringC__vtbl* ifce_System_Collections_Generic_IEnumeratorGSystem_StringC;
};
#endif
extern System_Type* System_Collections_Generic_IEnumerableGSystem_Int32C__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_ICollectionGSystem_Int32C__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IListGSystem_Int32C__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IReadOnlyCollectionGSystem_Int32C__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IReadOnlyListGSystem_Int32C__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Int32AY__type_HelloWorld_r00iaxum_dll;
extern const Void* System_Int32AY_vtable_System_Collections_Generic_IListGSystem_Int32C_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_Int32AY_vtable_System_Collections_Generic_IReadOnlyListGSystem_Int32C_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_Int32AY_vtable_System_ICloneable_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_Int32AY_vtable_System_Collections_IList_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_Int32AY_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_Int32AY
#define VTBL__System_Int32AY
struct System_Int32AY__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_Object_EqualsFSystem_ObjectN)(System_Object*, System_Object*);
    Int32 (*Int32_System_Object_GetHashCodeFN)(System_Object*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_Int32AY__getsizeFN)(System_Int32AY*);
    System_Type* (*System_Type_System_Int32AY__gettypeFN)(System_Int32AY*);
    System_Object* (*System_Object_System_Int32AY__dynifaceFSystem_TypeN)(System_Int32AY*, System_Type*);
    System_ICloneable__vtbl* ifce_System_ICloneable;
    System_Collections_IList__vtbl* ifce_System_Collections_IList;
    System_Collections_Generic_IListGSystem_Int32C__vtbl* ifce_System_Collections_Generic_IListGSystem_Int32C;
    System_Collections_Generic_IReadOnlyListGSystem_Int32C__vtbl* ifce_System_Collections_Generic_IReadOnlyListGSystem_Int32C;
};
#endif
extern System_Type* System_Collections_Generic_IEnumerableGSystem_ByteC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_ICollectionGSystem_ByteC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IListGSystem_ByteC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IReadOnlyCollectionGSystem_ByteC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_Collections_Generic_IReadOnlyListGSystem_ByteC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_ByteAY__type_HelloWorld_r00iaxum_dll;
extern const Void* System_ByteAY_vtable_System_Collections_Generic_IListGSystem_ByteC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ByteAY_vtable_System_Collections_Generic_IReadOnlyListGSystem_ByteC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ByteAY_vtable_System_ICloneable_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ByteAY_vtable_System_Collections_IList_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ByteAY_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_ByteAY
#define VTBL__System_ByteAY
struct System_ByteAY__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_Object_EqualsFSystem_ObjectN)(System_Object*, System_Object*);
    Int32 (*Int32_System_Object_GetHashCodeFN)(System_Object*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_ByteAY__getsizeFN)(System_ByteAY*);
    System_Type* (*System_Type_System_ByteAY__gettypeFN)(System_ByteAY*);
    System_Object* (*System_Object_System_ByteAY__dynifaceFSystem_TypeN)(System_ByteAY*, System_Type*);
    System_ICloneable__vtbl* ifce_System_ICloneable;
    System_Collections_IList__vtbl* ifce_System_Collections_IList;
    System_Collections_Generic_IListGSystem_ByteC__vtbl* ifce_System_Collections_Generic_IListGSystem_ByteC;
    System_Collections_Generic_IReadOnlyListGSystem_ByteC__vtbl* ifce_System_Collections_Generic_IReadOnlyListGSystem_ByteC;
};
#endif
extern System_Type* System_ArraySegmentGSystem_Int32C__type_HelloWorld_r00iaxum_dll;
extern const Void* System_ArraySegmentGSystem_Int32C_vtable_System_Collections_Generic_IListGSystem_Int32C_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_Int32C_vtable_System_Collections_Generic_IReadOnlyListGSystem_Int32C_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_Int32C_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_ArraySegmentGSystem_Int32C
#define VTBL__System_ArraySegmentGSystem_Int32C
struct System_ArraySegmentGSystem_Int32C__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_ArraySegmentGSystem_Int32C_EqualsFSystem_ObjectN)(System_ArraySegmentGSystem_Int32C*, System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_Int32C_GetHashCodeFN)(System_ArraySegmentGSystem_Int32C*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_Int32C__getsizeFN)(System_ArraySegmentGSystem_Int32C*);
    System_Type* (*System_Type_System_ArraySegmentGSystem_Int32C__gettypeFN)(System_ArraySegmentGSystem_Int32C*);
    System_Object* (*System_Object_System_ArraySegmentGSystem_Int32C__dynifaceFSystem_TypeN)(System_ArraySegmentGSystem_Int32C*, System_Type*);
    System_Collections_Generic_IListGSystem_Int32C__vtbl* ifce_System_Collections_Generic_IListGSystem_Int32C;
    System_Collections_Generic_IReadOnlyListGSystem_Int32C__vtbl* ifce_System_Collections_Generic_IReadOnlyListGSystem_Int32C;
};
#endif
extern System_Type* System_Collections_Generic_IEnumeratorGSystem_Int32C__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__type_HelloWorld_r00iaxum_dll;
extern const Void* System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_vtable_System_Collections_Generic_IEnumeratorGSystem_Int32C_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator
#define VTBL__System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator
struct System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_Object_EqualsFSystem_ObjectN)(System_Object*, System_Object*);
    Int32 (*Int32_System_Object_GetHashCodeFN)(System_Object*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__getsizeFN)(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator*);
    System_Type* (*System_Type_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__gettypeFN)(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator*);
    System_Object* (*System_Object_System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator__dynifaceFSystem_TypeN)(System_ArraySegmentGSystem_Int32C_ArraySegmentEnumerator*, System_Type*);
    System_Collections_Generic_IEnumeratorGSystem_Int32C__vtbl* ifce_System_Collections_Generic_IEnumeratorGSystem_Int32C;
};
#endif
extern System_Type* System_ArraySegmentGSystem_ByteC__type_HelloWorld_r00iaxum_dll;
extern const Void* System_ArraySegmentGSystem_ByteC_vtable_System_Collections_Generic_IListGSystem_ByteC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_ByteC_vtable_System_Collections_Generic_IReadOnlyListGSystem_ByteC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_ByteC_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_ArraySegmentGSystem_ByteC
#define VTBL__System_ArraySegmentGSystem_ByteC
struct System_ArraySegmentGSystem_ByteC__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_ArraySegmentGSystem_ByteC_EqualsFSystem_ObjectN)(System_ArraySegmentGSystem_ByteC*, System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_ByteC_GetHashCodeFN)(System_ArraySegmentGSystem_ByteC*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_ByteC__getsizeFN)(System_ArraySegmentGSystem_ByteC*);
    System_Type* (*System_Type_System_ArraySegmentGSystem_ByteC__gettypeFN)(System_ArraySegmentGSystem_ByteC*);
    System_Object* (*System_Object_System_ArraySegmentGSystem_ByteC__dynifaceFSystem_TypeN)(System_ArraySegmentGSystem_ByteC*, System_Type*);
    System_Collections_Generic_IListGSystem_ByteC__vtbl* ifce_System_Collections_Generic_IListGSystem_ByteC;
    System_Collections_Generic_IReadOnlyListGSystem_ByteC__vtbl* ifce_System_Collections_Generic_IReadOnlyListGSystem_ByteC;
};
#endif
extern System_Type* System_Collections_Generic_IEnumeratorGSystem_ByteC__type_HelloWorld_r00iaxum_dll;
extern System_Type* System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__type_HelloWorld_r00iaxum_dll;
extern const Void* System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_vtable_System_Collections_Generic_IEnumeratorGSystem_ByteC_interface_implHelloWorld_r00iaxum_dll[];
extern const Void* System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator_vtable_implHelloWorld_r00iaxum_dll[];
#ifndef VTBL__System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator
#define VTBL__System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator
struct System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__vtbl {
    System_String* (*System_String_System_Object_ToStringFN)(System_Object*);
    Boolean (*Boolean_System_Object_EqualsFSystem_ObjectN)(System_Object*, System_Object*);
    Int32 (*Int32_System_Object_GetHashCodeFN)(System_Object*);
    Void (*Void_System_Object_FinalizeFN)(System_Object*);
    Int32 (*Int32_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__getsizeFN)(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator*);
    System_Type* (*System_Type_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__gettypeFN)(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator*);
    System_Object* (*System_Object_System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator__dynifaceFSystem_TypeN)(System_ArraySegmentGSystem_ByteC_ArraySegmentEnumerator*, System_Type*);
    System_Collections_Generic_IEnumeratorGSystem_ByteC__vtbl* ifce_System_Collections_Generic_IEnumeratorGSystem_ByteC;
};
#endif
Void _gctors_for_CoreLib();
Void _gctors_for_HelloWorld_r00iaxum_dll();
#endif
